[package]
name = "anchor-client"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[dependencies]
anchor-codec = { path = "../codec" }
anchor-identity = { path = "../identity" }
anchor-proof = { path = "../proof" }
base64 = "0.23.1"
ed25519-dalek = "3.0.0"
jmt = "0.12.0"
rand = "0.10.2"
reqwest = { version = "0.13.5", default-features = false, features = ["query", "rustls"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tendermint = { version = "0.40.4", features = ["rust-crypto"] }
tendermint-light-client-verifier = { version = "0.40.4", features = ["rust-crypto"] }
thiserror = "2.0.20"

[dev-dependencies]
anchor-commitment = { path = "../commitment" }
anchor-testing = { path = "../testing" }
anyhow = "1.0.104"
jmt = { version = "0.12.0", features = ["mocks"] }
mockito = "1.7.2"
tokio = { version = "1", features = ["macros", "rt"] }
