[package]
name = "anchor-identity"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = { workspace = true }

[dependencies]
anchor-codec = { path = "../codec" }
blake3 = "1.8.7"
ed25519-dalek = "3.0.0"
minicbor = { version = "2.3.0", features = ["alloc"] }
p256 = "0.14.0"
thiserror = "2.0.20"

[dev-dependencies]
anyhow = "1.0.104"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
